/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2023-07-13 13:24:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>User-Page</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Link of JQuery cdn -->\r\n");
      out.write("    <script src= \"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"> </script>\r\n");
      out.write("<!-- Checkbox disable or enable -->        \r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t\t  $('#myCheckbox').click(function () {\r\n");
      out.write("\t\t    $('#myButton').prop(\"disabled\", !$(\"#myCheckbox\").prop(\"checked\")); \r\n");
      out.write("\t\t  })\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write(" \tfunction validateFields() {\r\n");
      out.write("\t\tvar location=document.getElementById(\"location\").value;\r\n");
      out.write("\t\tvar type=document.getElementById(\"type\").value;\r\n");
      out.write("\t\tvar classification=document.getElementById(\"classification\").value;\r\n");
      out.write("\t\tvar terms=document.getElementById(\"terms\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(location==\"\" || location==null && type==\"\" || type==null && classification==\"\" || classification==null && terms==\"\" || terms==null){\r\n");
      out.write("\t\t\tdocument.getElementById('validate').innerHTML=\"please fill the form\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if (location==\"\" || type ==\"\" || classification ==\"\" || terms ==\"\") {\r\n");
      out.write("\t\t\tdocument.getElementBy('validate').innerHTML=\"please fill the missing fields\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementBy('validate').innerHTML=\"\";\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write(" \tfunction EmailAjax(){\r\n");
      out.write(" \t\tconsole.log(\"EmailAjax logged-in\");\r\n");
      out.write(" \t\tvar email=document.getElementById(\"email\").value;\r\n");
      out.write(" \t\tvar url=\"http://localhost:8080/parking/validateEmail/\"+email;\r\n");
      out.write(" \t\tconsole.log(url);\r\n");
      out.write(" \t\tconst xmlHttp=new XMLHttpRequest();\r\n");
      out.write(" \t\txmlHttp.open(\"GET\", url);\r\n");
      out.write(" \t\txmlHttp.send();\r\n");
      out.write(" \t\txmlHttp.onload=function(){\r\n");
      out.write(" \t\t\tconsole.log(this.responseText);\r\n");
      out.write(" \t\t\tdocument.getElementById('display').innerHTML=this.responseText;\r\n");
      out.write(" \t\t\tdocument.getElementById('here').innerHTML=\"\";\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction ajaxWithObj() {\r\n");
      out.write(" \t\tconsole.log(\"ajaxWithObj logged-in\")\r\n");
      out.write(" \t\tvar location=document.getElementById(\"location\").value;\r\n");
      out.write(" \t\tvar type=document.getElementById(\"type\").value;\r\n");
      out.write(" \t\tvar classification=document.getElementById(\"classification\").value;\r\n");
      out.write(" \t\tvar terms=document.getElementById(\"terms\").value;\r\n");
      out.write(" \t\tvar url=\"http://localhost:8080/parking/getPriceAndDiscount/\"+location+\"/\"+type+\"/\"+classification+\"/\"+terms\r\n");
      out.write(" \t\tconsole.log(url);\r\n");
      out.write(" \t\tconst xmlHttp=new XMLHttpRequest();\r\n");
      out.write(" \t\txmlHttp.open(\"GET\", url);\r\n");
      out.write(" \t\txmlHttp.send();\r\n");
      out.write(" \t\txmlHttp.onload=function(){\r\n");
      out.write(" \t\t\tconsole.log(this.responseText);\r\n");
      out.write(" \t\t\tvar obj=JSON.parse(this.responseText);\r\n");
      out.write(" \t\t\tconsole.log(obj.price);\r\n");
      out.write(" \t\t\tconsole.log(obj.discount);\r\n");
      out.write(" \t\t\tdocument.getElementById(\"price\").value=obj.price;\r\n");
      out.write(" \t\t\tdocument.getElementById(\"discount\").value=obj.discount;\r\n");
      out.write(" \t\t\tvar totalAmount=obj.price-((obj.price*obj.discount)/100);\r\n");
      out.write(" \t\t\tconsole.log(totalAmount);\r\n");
      out.write(" \t\t\tdocument.getElementById(\"totalAmount\").value = totalAmount;\r\n");
      out.write(" \t\t}\r\n");
      out.write("\t}\r\n");
      out.write(" </script>\r\n");
      out.write("<!-- Link of Bootstrap cdn -->     \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"Parking.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"fixed-header\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark bg-secondary justify-content-between\">\r\n");
      out.write("\t\t\t<img src=\"https://w7.pngwing.com/pngs/974/17/png-transparent-car-park-parking-computer-icons-parking-text-rectangle-logo-thumbnail.png\" alt=\"\" width=\"60\" height=\"60\"> \r\n");
      out.write("\t\t    <a href=\"User.jsp\" class=\"btn btn-info\" type=\"button\">Home</a>\r\n");
      out.write("\t\t    <a href=\"UserLogin.jsp\" class=\"btn btn-info\" type=\"button\" style=\"margin-right: 1100px;\">Login</a>\r\n");
      out.write("\t\t</nav>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<form action=\"user\" method=\"post\" onsubmit=\"return validateFields()\" style=\"background-color: white; margin-top: 10px;margin-bottom: 10px; margin-left: 200px; margin-right: 200px; border: 1px solid black; border-radius: 10px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<span style=\"color: green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usermsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> \t \r\n");
      out.write("\t \t<span style=\"color: red;\" id=\"display\"></span><a id=\"here\" href=\"UserLogin.jsp\"></a>\r\n");
      out.write("\t\t<h1 style=\"color: red; text-align: center;\" >User Information</h1>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<label for=\"name\"><b>User Name</b></label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" placeholder=\"Enter Name\" class=\"form-control\" required=\"required\">\r\n");
      out.write("\t\t\t<label for=\"email\"><b>User Email</b></label>\r\n");
      out.write("\t\t\t<input type=\"email\" name=\"email\" placeholder=\"Enter Email\" class=\"form-control\" onchange=\"EmailAjax()\" id=\"email\" required=\"required\">\r\n");
      out.write("\t\t\t<label for=\"mobile\"><b>User Mobile</b></label>\r\n");
      out.write("\t\t\t<input type=\"number\" name=\"mobile\" placeholder=\"Enter Mobile\" class=\"form-control\" required=\"required\" >\r\n");
      out.write("\t\t\t<label for=\"location\"><b>Vehicle Location</b></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"location\" class=\"form-control\" id=\"location\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">Location</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Rajaji-Nagar\">Rajaji-Nagar</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"kurubarahalli\">Kurubarahalli</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"btm\">BTM</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<label for=\"type\"><b>Vehicle Type</b></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"type\" class=\"form-control\" id=\"type\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">type</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2 wheeler\">2-Wheeler</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4 wheeler\">4-wheeler</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<label for=\"classification\"><b>Vehicle Classification</b></label>\t\r\n");
      out.write("\t\t\t\t\t<select name=\"classification\" class=\"form-control\" id=\"classification\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">classification</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"bmw\">BMW</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"dastun\">Dastun</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"benz\">Benz</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"bike\">Bike</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<label for=\"terms\"><b>Vehicle Terms</b></label>\t\t\r\n");
      out.write("\t\t\t\t\t<select name=\"terms\" class=\"form-control\" onchange=\"ajaxWithObj()\" id=\"terms\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">terms</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1-day\">1-Day</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"7-day\">7-Days</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"15-day\">15-Days</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"30-day\">30-Days</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"90-day\">90-Days</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"180-day\">180-Days</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"365-day\">365-Days</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<label for=\"price\"><b> User Price</b></label>\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"price\" class=\"form-control\" placeholder=\"price\" id=\"price\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t<label for=\"discount\"><b>User Discount</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"discount\" class=\"form-control\" placeholder=\"discount\" id=\"discount\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t<label for=\"totalAmount\"><b>User Total Amount</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"totalAmount\" class=\"form-control\" placeholder=\"Total Amount\" id=\"totalAmount\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t<div class=\"form-group form-check\">\r\n");
      out.write("\t\t\t    <input type=\"checkbox\" class=\"form-check-input\" id=\"myCheckbox\">\r\n");
      out.write("\t\t\t    <label class=\"form-check-label\" for=\"myCheckbox\">Check for agreement</label>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t \t\t\t <input type=\"submit\" value=\"Submit\" class=\"btn btn-info\" id=\"myButton\" disabled><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<div class=\"fixed-footer\">\r\n");
      out.write("<footer class=\"bg-secondary text-white\">\r\n");
      out.write("    <div class=\"text-center p-3\" style=\"background-color: secondary;\">\r\n");
      out.write("      © 2023 Copyright:\r\n");
      out.write("      <a class=\"text-white\" href=\"https://irfan.xworkz@gmail.com/\">irfan.xworkz@gmail.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</div> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
