/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2023-07-13 14:16:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>AdminPanel</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"Parking.css\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar mins=5;\r\n");
      out.write("\t\tvar secs=mins*60;\r\n");
      out.write("\t\tfunction countdown(){\r\n");
      out.write("\t\t\tsetTimeout('Decrement()', 60);\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\tfunction Decrement(){\r\n");
      out.write("\t\t\t\tif(document.getElementById){\r\n");
      out.write("\t\t\t\t\tminutes=document.getElementById(\"minutes\");\r\n");
      out.write("\t\t\t\t\tseconds=document.getElementById(\"seconds\");\r\n");
      out.write("\t\t\t\t\tif(seconds<59){\r\n");
      out.write("\t\t\t\t\t\tseconds.value=secs;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tminutes.value=getminutes();\r\n");
      out.write("\t\t\t\t\t\tseconds.value=getseconds();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(min<1) {\r\n");
      out.write("\t\t\t\t\t\tminutes.style.color=\"red\";\r\n");
      out.write("\t\t\t\t\t\tseconds.style.coor=\"red\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(mins<0){\r\n");
      out.write("\t\t\t\t\t\talert('time up');\r\n");
      out.write("\t\t\t\t\t\tminutes.value=0;\r\n");
      out.write("\t\t\t\t\t\tseconds.value=0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tsecs--;\r\n");
      out.write("\t\t\t\t\t\tsetTimeout('Decrement()', 1000);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction getminutes(){\r\n");
      out.write("\t\t\t\tmins=Math.floor(secs/60);\r\n");
      out.write("\t\t\t\treturn mins;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction getseconds(){\r\n");
      out.write("\t\t\t\tretun secs-Math.round(mins*60);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"fixed-header\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark bg-secondary justify-content-between\">\r\n");
      out.write("\t\t\t<img src=\"https://w7.pngwing.com/pngs/974/17/png-transparent-car-park-parking-computer-icons-parking-text-rectangle-logo-thumbnail.png\" alt=\"\" width=\"60\" height=\"60\">\r\n");
      out.write("\t\t    <a  href=\"Home.jsp\" class=\"btn btn-info\" type=\"button\" style=\"margin-right: 1150px;\">Home</a>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("</header>\r\n");
      out.write("<body >\r\n");
      out.write(" \t<div class=\"container\">\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user-login\"  style=\"background-color: white; margin-top: 50px; margin-left: 200px; margin-right: 200px; border: 1px solid black; border-radius: 10px;\">\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<span></span><br>\r\n");
      out.write("\t\t\t\t<span style=\"color: green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${otpmsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${otpmsg1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<h1 style=\"text-align: center; color: red;\">User Login Panel</h1>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<label for=\"email\"><b>Email Address</b></label>\t\r\n");
      out.write("\t\t\t    <input type=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Enter Email\">\r\n");
      out.write("\t\t\t    <input type=\"submit\" value=\"Send OTP\" name=\"otp\"  onclick=\"countdown();\" class=\"btn btn-info\" >\r\n");
      out.write("\t\t\t    <span style=\"color: red;\"> \r\n");
      out.write("\t\t\t    <input id=\"minutes\" type=\"text\" style=\"width: 5%; border: none; font-size: 16px; font-weight: bold;\"> \r\n");
      out.write("\t\t\t    <font size=\"5\"> : </font> \r\n");
      out.write("\t\t\t    <input id=\"seconds\" type=\"text\" style=\"width: 5%; border: none; font-size: 16px; font-weight: bold;\"> </span><br><br>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label for=\"otp\"><b>OTP</b></label>    \r\n");
      out.write("\t\t\t    <input type=\"text\" name=\"otp\" class=\"form-control\" placeholder=\"Enter OTP\"><br>\r\n");
      out.write("\t\t\t \t <input type=\"submit\" name=\"login\" value=\"Login\" class=\"btn btn-info\"><br>\r\n");
      out.write("\t\t\t \t<span></span><br>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("\t<div class=\"fixed-footer\">\r\n");
      out.write("\t\t<footer class=\"bg-secondary text-white\">\r\n");
      out.write("\t\t    <div class=\"text-center p-3\" style=\"background-color: secondary;\">\r\n");
      out.write("\t\t      © 2023 Copyright:\r\n");
      out.write("\t\t      <a class=\"text-white\" href=\"https://irfan.xworkz@gmail.com/\">irfan.xworkz@gmail.com</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t </footer>\r\n");
      out.write("\t</div>\t \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
